CREATE TABLE IF NOT EXISTS users (
  id BLOB PRIMARY KEY, -- A randomly-generated ID.
  handle VARCHAR(65535) UNIQUE NOT NULL, -- User's actual username
  name VARCHAR(65535) NOT NULL, -- User's display name
  local BOOLEAN NOT NULL, -- A boolean indicating if the user is from here or from somewhere else.
  email VARCHAR(255), -- To store the user's email
  bio VARCHAR(65535), -- To store the user's biography
  password VARCHAR(65535), -- Stores a password hash, the hash is generated by crypto.hash() which is based on nimcrypto's PBKDF2 implementation
  salt VARCHAR(65535), -- A password salt, generated by data.newUser().
  is_frozen BOOLEAN, -- Indicates if a user is banned. This prevents them from logging in.
);
  
CREATE TABLE IF NOT EXISTS posts (
  id BLOB PRIMARY KEY,
  sender VARCHAR(65535) NOT NULL,
  written TIMESTAMP NOT NULL,
  updated TIMESTAMP,
  recipients VARCHAR(65535),
  post VARCHAR(65535) NOT NULL
);

-- Inserting some generic users for testing
-- The "users" table should be able to handle any user
-- even if they are not from this server
--INSERT INTO users (id, handle, name, local, email, bio, password) VALUES ("1", "kropotkin", "Peter Kropotkin", true, "peter.kropotkin@moscow.commune.i2p","I love to help others and I inspire people to help each other\nI thought I might explore this platform\nI don't know how it works!", "BetterBlackANDRed");

--INSERT INTO users (id, handle, name, local, email, bio, password) VALUES ("2", "lenin@communism.rocks", "Vladimir Lenin", false, "vladimir.lenin@cp.su", "Chairman of the Council of People's Commissars of the Soviet Union\n\nAny comments that are negative of the CCCP or CPSU will be reported.", "BetterRedThanDead");

--INSERT INTO users (id, handle, name, local, email, bio, password) VALUES ("3", "aynrand@google.google","Ayn Rand", false, "aynrand@aynrand.google.site","\nAuthor of The Fountainhead and Atlas Shrugged.\nSocial democrats, socialists, communists, anarchists or anyone who has morals:\nDo not interact or you will be reported to Google's Unsafe Persons Registry.","BetterDeadThanRed");